[build]
  command = "npm run build && php -S 0.0.0.0:8000 -t build"

[dev]
  command = "npm start"
  functions = "api/"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/:splat"
  status = 200